### PR TITLE
Rustic API

### PR DESCRIPTION
**Pull request by jameysharp**
I am very excited to see this crate in progress!

I started reviewing the unit tests in #2 and concluded that it'd probably help to discuss what the crate's API should look like before writing tests.

So this pull request contains my proposal for a fairly Rust-like API which can do the same things as the documented parts of https://github.com/kornelski/http-cache-semantics. I've included documentation, although executable code samples would be a huge improvement there. This still doesn't provide any implementations (except for `SimpleHeaders`, which is pretty trivial) or tests, but I think it provides a more solid foundation for writing tests.

I'd love to have a conversation about whether this is actually the right API! Please throw questions at me. :smile:

### CODE REVIEW

**Comment by jameysharp** [comment]
I definitely like the idea of using someone else's definitions! I hadn't seen that crate before so I've just spent some time digging through it. I have some minor concerns about excessive cleverness in the implementation in places, but it seems quite reasonable overall. I quite like its representation of status codes and methods especially.

There's a question of design goals though. That http crate is strongly opinionated about how to represent each of these concepts, which makes it easy to use so long as everything uses it… but if you need a different representation somewhere, you have to do a big conversion to make the types match up.

In my proposal I was trying to keep this API independent of representation so that a small amount of glue would let you use it with any other library. That would make this harder to use but more efficient if the ecosystem doesn't go uniformly to a single representation such as the http crate.

I honestly don't know which is better?

In the interests of focusing on making this crate correct, I suppose that using the other crate's definitions keeps the scope of this work smaller. So that's probably the right plan at least initially. Maybe once there are some folks using it we'll find out that relying on the http crate is too limiting and change the API then.

**Comment by zkat** [comment]
One big reason for using the http crate is that type conversions would be minimal -- it's what `surf` uses, and by extension, [`surf-middleware-cache`](https://github.com/zkat/surf-middleware-cache), which is what this crate is being written for use with in the first place. So I'm definitely motivated here to not have to do a bunch of type translation :P

**Comment by jameysharp** [comment]
Okay, you've convinced me :grin: 

I've pushed an additional commit to remove my custom types and use types from the `http` crate instead. The result is a lot shorter, heh…

Separately, I've just removed the `extern crate` declaration because in 2018 edition Rust those aren't necessary. Pulling in the `lazy_static` macro works via a `use` declaration now instead. The earliest commit on this branch also removes the extra `mod http_cache_semantics` so that `cargo doc` will actually see the declarations. And I've been running `cargo fmt` before each commit to make code style consistent with Rust conventions, since I can never remember precisely what those are. I forgot to mention these changes in my summary of this pull request.

**Comment by non-binary** [comment]
This looks good, @jameysharp. I've changed the base branch to `nb/tests` instead of `master` given there's a bunch of related work going on there. Do you mind fixing the merge conflicts please and we can get this merged/move onto the next steps?

I'm currently preoccupied with job searching so I don't have a lot of time/energy for this but happy to answer questions and/or merge things. Let me know if you'd like contributor rights to the repository. :)

**Comment by zkat** [comment]
@non-binary can we both get collaborator rights, maybe? <3

**Comment by jameysharp** [comment]
Apparently I pulled in some commits you had on `master` but not on `nb/tests`? I guess that's fine… :man_shrugging: 

Anyway, I've merged it! The tests don't compile now because I didn't change them to match the API changes I made yet, but the module does compile otherwise.

I guess I was hoping for a little more conversation about whether I've gone a good direction though. I wasn't trying to come in and say "no, this is definitely how this should work." :sweat_smile: Have either of you had an opportunity to look over the API that I proposed?

On a related note I almost don't want commit rights because I'd really prefer to have somebody else reviewing my patches? :man_shrugging: I won't turn it down though.

**Comment by zkat** [comment]
This looks really good just from reading through it. I'll need to sit down and see how this API would fit into the middleware before giving you a proper review. But yeah, this looks great!

**Comment by non-binary** [comment]
I've sent collaborator invites to both of you. @jameysharp Feel free to still add one of us as reviewers on your pull requests. Just gives you the flexibility in case you need to do something when we're not available i guess. I don't really have the energy to look through it right now so I'll let @zkat do it when they get to it or will look at it if it hasn't been once I have more energy. :)

**Comment by non-binary** [comment]
Going to squash into `nb/tests`. If you could continue working from that branch, that'd be awesome.

**Pull request merged**
